### ISSUE TITLE
is there render in this client

### ISSUE THREAD

**Issue by codingwatching** [Twometer/Mycraft#1]
Hi @Twometer 
I can import project into android studio and run the game
But after login in to server i only see the cursor and the pad, nothing from block and world get render
Is that a bugs or something i miss from the setup?
Thank you so much!

**Comment by Twometer** [comment]
Hey,

Yes, the client can render the world in 3D. also there is not much more to the setup than running it in Android Studio.
What Minecraft version are you using for your server?
Also, are there any log outputs in the Android Studio logcat?

**Comment by codingwatching** [comment]
Hi @Twometer 
Ahhh yes it is because my server do not start, sorry it is my fault
2021-06-16 11:34:15.840 14701-14995/de.twometer.mycraft W/System.err: java.net.ConnectException: failed to connect to /192.168.98.47 (port 25565) from /:: (port 47082): connect failed: ECONNREFUSED (Connection refused)

I try to download server.jar version 1.8 and run by command java -jar server.jar
The server can run but maybe i do not config it correctly

Can you recommend any easy server that our client can run well to getting start?

![image](https://user-images.githubusercontent.com/85933804/122158633-320c9100-ce97-11eb-8e72-aed2c02950ab.png)

**Comment by codingwatching** [comment]
Update:
After argee the eula, I can run the server and here is the error log from android studio
```
2021-06-16 11:41:43.844 15334-15437/de.twometer.mycraft E/AndroidRuntime: FATAL EXCEPTION: Thread-4
    Process: de.twometer.mycraft, PID: 15334
    java.lang.RuntimeException: VarInt is too big
        at de.twometer.mycraft.net.socket.McSocket.receiveVarInt(McSocket.java:39)
        at de.twometer.mycraft.net.McClient$2.run(McClient.java:61)
        at java.lang.Thread.run(Thread.java:920)
```

Here is the log from server console

```
[11:39:28 INFO]: Preparing level "world"
[11:39:28 INFO]: Preparing start region for level 0
[11:39:29 INFO]: Preparing spawn area: 18%
[11:39:30 INFO]: Preparing spawn area: 44%
[11:39:31 INFO]: Preparing spawn area: 67%
[11:39:32 INFO]: Preparing spawn area: 91%
[11:39:33 INFO]: Done (4.562s)! For help, type "help" or "?"
[11:39:38 INFO]: --- Showing help page 1 of 9 (/help <page>) ---
[11:39:38 INFO]: /achievement <give|take> <stat_name|*> [player]
[11:39:38 INFO]: /ban <name> [reason ...]
[11:39:38 INFO]: /ban-ip <address|name> [reason ...]
[11:39:38 INFO]: /banlist [ips|players]
[11:39:38 INFO]: /blockdata <x> <y> <z> <dataTag>
[11:39:38 INFO]: /clear [player] [item] [data] [maxCount] [dataTag]
[11:39:38 INFO]: /clone <x1> <y1> <z1> <x2> <y2> <z2> <x> <y> <z> [mode]
[11:40:43 INFO]: com.mojang.authlib.GameProfile@3adbfbec[id=<null>,name=Twometer,properties={},legacy=false] (/192.168.98.39:47104) lost connection: Internal Exception: io.netty.handler.timeout.ReadTimeoutException
[11:41:43 INFO]: com.mojang.authlib.GameProfile@733683b1[id=<null>,name=Twometer,properties={},legacy=false] (/192.168.98.39:47106) lost connection: Internal Exception: io.netty.handler.timeout.ReadTimeoutException
```

If it is not server version that can run with client, please help me find some server that fit for our client.
Thank you so much!

**Comment by Twometer** [comment]
You are using the right version of the server.

The problem you have occurs, because the Minecraft server by default requires an encrypted connection that is authenticated with a real Mojang account. The Mycraft client currently doesn't support encryption or Mojang auth, and is running in Minecraft's so-called "offline mode". 

To get your server to accept these types of offline-mode connections, you should open the `server.properties` file that was generated next to the server jar file and set the `online-mode` property to `false`.

Then, restart the server and you should be able to connect :-)

**Comment by codingwatching** [comment]
Hi @Twometer 
Thank you so much for the help, after change online-mode to false, i can now connect to the game but in the client, there still only sky with cursor, no blocks or character. Here is the log

Client log
```
2021-06-17 09:51:36.631 29102-29102/? I/libc: SetHeapTaggingLevel: tag level set to 0
2021-06-17 09:51:36.633 29102-29102/? I/wometer.mycraf: Late-enabling -Xcheck:jni
2021-06-17 09:51:36.679 29102-29102/de.twometer.mycraft D/CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10274; state: DISABLED
2021-06-17 09:51:36.685 29102-29102/de.twometer.mycraft D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
2021-06-17 09:51:36.717 29102-29102/de.twometer.mycraft I/TetheringManager: registerTetheringEventCallback:de.twometer.mycraft
2021-06-17 09:51:36.719 29102-29102/de.twometer.mycraft V/GraphicsEnvironment: ANGLE Developer option for 'de.twometer.mycraft' set to: 'default'
2021-06-17 09:51:36.719 29102-29102/de.twometer.mycraft V/GraphicsEnvironment: Updatable production driver is not supported on the device.
2021-06-17 09:51:36.720 29102-29102/de.twometer.mycraft D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2021-06-17 09:51:36.721 29102-29102/de.twometer.mycraft D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2021-06-17 09:51:36.773 29102-29102/de.twometer.mycraft W/wometer.mycraf: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
2021-06-17 09:51:36.774 29102-29102/de.twometer.mycraft W/wometer.mycraf: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
2021-06-17 09:51:36.875 29102-29121/de.twometer.mycraft I/AdrenoGLES-0: QUALCOMM build                   : 85da404, I46ff5fc46f
    Build Date                       : 11/30/20
    OpenGL ES Shader Compiler Version: EV031.31.04.01
    Local Branch                     : promo490_3_Google
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
2021-06-17 09:51:36.875 29102-29121/de.twometer.mycraft I/AdrenoGLES-0: Build Config                     : S P 10.0.4 AArch64
2021-06-17 09:51:36.875 29102-29121/de.twometer.mycraft I/AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
2021-06-17 09:51:36.880 29102-29121/de.twometer.mycraft I/AdrenoGLES-0: PFP: 0x016ee189, ME: 0x00000000
2021-06-17 09:51:36.882 29102-29121/de.twometer.mycraft W/AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
2021-06-17 09:51:36.882 29102-29121/de.twometer.mycraft W/AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
2021-06-17 09:51:36.890 29102-29121/de.twometer.mycraft I/Gralloc4: mapper 4.x is not supported
2021-06-17 09:51:36.891 29102-29121/de.twometer.mycraft W/Gralloc4: allocator 4.x is not supported
2021-06-17 09:51:36.969 29102-29125/de.twometer.mycraft D/MyCraft_Native: Loading shader gui
2021-06-17 09:51:36.976 29102-29125/de.twometer.mycraft D/MyCraft_Native: Loading shader texturedgui
2021-06-17 09:51:36.982 29102-29125/de.twometer.mycraft D/MyCraft_Native: Loading shader terrain
2021-06-17 09:51:48.998 29102-29102/de.twometer.mycraft D/CompatibilityChangeReporter: Compat change id reported: 179274888; UID 10274; state: LOGGED
2021-06-17 09:51:49.704 29102-29102/de.twometer.mycraft D/MyCraft_Native: Placing a block now
2021-06-17 09:51:52.117 29102-29102/de.twometer.mycraft D/MyCraft_Native: Placing a block now
2021-06-17 09:52:05.255 29102-29102/de.twometer.mycraft D/MyCraft_Native: Placing a block now
2021-06-17 09:52:05.575 29102-29102/de.twometer.mycraft D/MyCraft_Native: Placing a block now
2021-06-17 09:52:07.268 29102-29125/de.twometer.mycraft D/MyCraft_Native: Loading shader gui
2021-06-17 09:52:07.269 29102-29125/de.twometer.mycraft D/MyCraft_Native: Loading shader texturedgui
2021-06-17 09:52:07.269 29102-29125/de.twometer.mycraft D/MyCraft_Native: Loading shader terrain
2021-06-17 09:52:08.909 29102-29102/de.twometer.mycraft D/MyCraft_Native: Placing a block now
2021-06-17 09:52:09.224 29102-29102/de.twometer.mycraft D/MyCraft_Native: Placing a block now
2021-06-17 09:52:24.009 29102-29102/de.twometer.mycraft D/MyCraft_Native: Placing a block now
2021-06-17 09:52:27.915 29102-29102/de.twometer.mycraft D/MyCraft_Native: Placing a block now
2021-06-17 09:52:49.376 29102-29137/de.twometer.mycraft W/System.err: java.net.SocketException: Connection reset
2021-06-17 09:52:49.376 29102-29137/de.twometer.mycraft W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:215)
2021-06-17 09:52:49.376 29102-29137/de.twometer.mycraft W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:144)
2021-06-17 09:52:49.376 29102-29137/de.twometer.mycraft W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:229)
2021-06-17 09:52:49.377 29102-29137/de.twometer.mycraft W/System.err:     at de.twometer.mycraft.net.socket.McSocket.receiveVarInt(McSocket.java:33)
2021-06-17 09:52:49.377 29102-29137/de.twometer.mycraft W/System.err:     at de.twometer.mycraft.net.McClient$2.run(McClient.java:61)
2021-06-17 09:52:49.377 29102-29137/de.twometer.mycraft W/System.err:     at java.lang.Thread.run(Thread.java:920)

```


Server 

```
[09:51:05 INFO]: Starting minecraft server version 1.8
[09:51:06 INFO]: Loading properties
[09:51:06 INFO]: Default game type: SURVIVAL
[09:51:06 INFO]: Generating keypair
[09:51:06 INFO]: Starting Minecraft server on *:25565
[09:51:06 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[09:51:06 WARN]: The server will make no attempt to authenticate usernames. Beware.
[09:51:06 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[09:51:06 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[09:51:06 INFO]: Preparing level "world"
[09:51:06 INFO]: Preparing start region for level 0
[09:51:06 INFO]: Done (0.603s)! For help, type "help" or "?"
[09:51:15 WARN]: Time ran backwards! Did the system time change?
[09:51:38 INFO]: Twometer[/192.168.99.55:39648] logged in with entity id 79 at (165.5, 63.0, 284.5)
[09:51:38 INFO]: Twometer joined the game
[09:52:08 INFO]: Twometer lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[09:52:08 INFO]: Twometer left the game

```

**Comment by Twometer** [comment]
That's a little  weird... I think there still has to be something wrong with the connection, beacuse the server registered the Disconnect much earlier than the  client. Can you try disabling the Firewall on the computer that hosts the server? I know that that can be a problem with Minecraft servers running under Windows at least.
Also, what Android version are you running? Are you running it on a real device or on an emulator?
I haven't worked on this project in over a year, so maybe something changed during that time :)

**Comment by codingwatching** [comment]
Hi @Twometer 
Yes you are right about the android version, I am testing on real device android 12
After change back to android 10, I can see the world render now, thank you for the support!

By the way, is https://github.com/Twometer/NextCraft new version that you are develop?
Is there any chance for NextCraft running on android device? I am looking for a Minecraft version that can run well on Android
Thank you!

**Comment by Twometer** [comment]
Hi,
yes NextCraft is a newer version of the client that I developed. It however still runs on Minecraft version 1.8, but with newer rendering and faster and better code.
I think it should be possible for NextCraft to run on Android, since OpenGL code is mostly platform agnostic. However, one would still have to make a port and implement the touch controls.

**Comment by takaaptech** [comment]
Thank you!

**Comment by codingwatching** [comment]
@Twometer  Awesome! I will follow up the NextCraft!
One more thing may i ask, why we keep version at Minecraft version 1.8? What is the advance of 1.8 or nice feature about that version?
Thank you so much!

**Comment by Twometer** [comment]
Glad you like it :) - The main reason for using 1.8 is that when I started working with Minecraft Networking, this was a very new version. I therefore know the protocol of version 1.8 very well and it made it easier for me to write clients for that version. However, I one day would like to create a client for newer versions

**Comment by codingwatching** [comment]
Hi @Twometer Thank you! I will ask some questions about networking in NextCraft. I hope you can help, I am a newbie  in Minecraft and Network
